---
apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: repository
spec:
  giteaImageTag: 1.20.0
  giteaImagePullPolicy: Always
  postgresqlVolumeSize: 4Gi
  giteaVolumeSize: 4Gi
  giteaSsl: True
