---
apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: repository
  labels:
    app.kubernetes.io/name: gitea-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  giteaImageTag: 1.23.7
  giteaImagePullPolicy: Always
  postgresqlVolumeSize: 4Gi
  giteaVolumeSize: 4Gi
  giteaSsl: True
