# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/gitea-operator.clusterserviceversion.yaml
- ../default
- ../samples
- ../scorecard

patches:
- path: ./patches/csv.yaml
  target:
    group: operators.coreos.com
    version: v1alpha1
    kind: ClusterServiceVersion
    name: gitea-operator.v0.0.0
    namespace: placeholder

